accounts/urls.py
# accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

notes_api/urls.py
from django.urls import path 
from django.contrib.auth.views import LogoutView
from django.urls import path, include

from . import views 
app_name = 'notes_api'
urlpatterns = [
    path('', views.NoteList.as_view(), name='home'),
    path('detail/<int:pk>/', views.NoteDetail.as_view(), name='note_detail'),
    path('add_note/', views.add_note, name='add_note'),
    path('delete_note/<int:pk>/', views.delete_note, name='delete_note'),
    path('edit/<int:pk>/', views.EditNote.as_view(), name='edit_note'),
    path('edit/<int:pk>/update_note', views.update_note, name='update_note'),
]

notes_app/urls.py
from django.contrib import admin
from django.urls import path, include
from notes_api import views

urlpatterns = [
    path('', views.NoteList.as_view(), name='home'),
    path('notes_api/', include('notes_api.urls')),
    path('social/', include('social.urls')),
    path("accounts/", include("accounts.urls")),  
    path("accounts/", include("django.contrib.auth.urls")),  
    path('admin/', admin.site.urls),
]

social/urls.py
from django.urls import path 
from django.urls import path, include
from . import views 

app_name = 'social'
urlpatterns = [
    path('', views.UserList.as_view(), name='home'),
]

notes_api/models.py
from django.db import models
from django.contrib.auth.models import User

# model for the notes
class Note(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="note", null=True) # <--- added
    title = models.CharField(max_length=100, null=True, blank=True)
    body = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # return string representation of the object
    def __str__(self):
        return self.title
    

class Item(models.Model):
    note = models.ForeignKey(Note, on_delete=models.CASCADE)
    text = models.CharField(max_length=300)
    complete = models.BooleanField()

    def __str__(self):
	    return self.text

social/models.py
from django.db import models

# Create your models here.

notes_api/forms.py
from django import forms
from django.forms import ModelForm
from .models import Note

class NoteForm(ModelForm):
     class Meta:
        model = Note
        exclude = ('user',)
        fields = ["title", "body"]

accounts/views.py
# accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

notes_api/views.py
from django.shortcuts import render
# from rest_framework import generics
from django.views import generic
from .models import Note
from .serializers import NoteSerializer
from django.shortcuts import get_object_or_404, render
from .forms import NoteForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# @permission_classes([IsAuthenticated])
class NoteList(generic.ListView):
    template_name = "notes_api/index.html"
    context_object_name = "latest_notes_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        # this gets all notes
        # return Note.objects.all().order_by('-updated')
        user_notes = Note.objects.filter(user=self.request.user)
        return user_notes
        

    # this function will return the notes list 
# @permission_classes([IsAuthenticated])
class NoteDetail(generic.DetailView):
    queryset = Note.objects.all()
    context_object_name = 'note_detail'
    template_name = "notes_api/detail.html"

class EditNote(generic.DetailView):
    queryset = Note.objects.all()
    context_object_name = 'note_detail'
    template_name = "notes_api/edit.html"

def update_note(request, pk):
    print("request", request)
    if request.method=="POST":
        note = NoteForm(request.POST)
        if note.is_valid():
            note.save()
            return HttpResponseRedirect(reverse('notes_api:home'))

def add_note(request):
    if request.method=="POST":
        form = NoteForm(request.POST)
        # print("note", note)
        if form.is_valid():
            note = form.save(commit=False)
            note.user = request.user
            # print("request.user", request.user)
            note.save()
            request.user.note.add(note)
            return HttpResponseRedirect(reverse('notes_api:home'))

def delete_note(request, pk):
    note = get_object_or_404(Note, pk=pk)
    note.delete()
    return HttpResponseRedirect(reverse('notes_api:home'))

social/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.models import User


# Create your views here.
class UserList(generic.ListView):
    template_name = "social/index.html"
    context_object_name = 'all_users'
    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        all_users = User.objects.all()
        print("all_users", all_users)
        return all_users
        # this gets all notes
        # return Note.objects.all().order_by('-updated')
        # return None

notes_api/templates/notes_api/detail.html
{% load static %}

<html>
    <header>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </header>
    <body>
        {% if note_detail %}
            <ul class="list-group">
                <li class="list-group-item">
                    <h2>{{note_detail.title}}</h2>
                </li>
                <li class="list-group-item">
                    <p>
                        {{note_detail.body}}
                    </p>
                </li>
                <li class="list-group-item">
                    <b>
                        Created:
                    </b>
                    <p>
                        {{note_detail.created}}
                    </p>
                    <b>
                        Updated:
                    </b>
                    <p>
                        {{note_detail.updated}}
                    </p>
                </li>
            </ul>
        {% else %}
        <p>No polls are available.</p>
    </body>
{% endif %}

</html>

notes_api/templates/notes_api/edit.html
<html>
    <header>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </header>
    <body>
        <h1>Update Note</h1>
        <form class="form-group" action="update_note" method="post">
            {% csrf_token %}
            Title:<br>
            <input class="form-control" name="title" value="{{ note_detail.title }}">
            <br><br>
            Body:<br>
            <input class="form-control" name="body" value="{{ note_detail.body }}">
            <br><br>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </body>
</html>

notes_api/templates/notes_api/index.html
{% load socialaccount %}

{% load static %}

<html>
    <header>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </header>
    <style>
        body {
            padding-top: 60px;
            padding-left: 60px;
            padding-right: 60px;
        }
    </style>
    <body>
        {% if user.is_authenticated %}
            <p>Welcome, You are logged in as {{ user.username }}</p>
            <a href="{% url 'logout' %}">Logout</a>
            <div>
                <h1>Notes</h1>
                {% if latest_notes_list %}
                <ul class="list-group">
                    {% for note in latest_notes_list %}
                        <li class="list-group-item">
                            <a href="{% url 'notes_api:note_detail' note.id %}"  style="display: inline-block; margin-right: 50px;">{{ note.title }}</a>
                            <form class="form-group" action="{% url 'notes_api:edit_note' note.id%}"  style="display: inline-block;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary">Edit</button>
                            </form>
                            <form class="form-group" action="{% url 'notes_api:delete_note' note.id%}"  style="display: inline-block;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                            <form class="form-group" action="{% url 'social:home' %}"  style="display: inline-block;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-success">Share</button>
                            </form>
                        </li>
                    {% endfor %}
                </ul>
                {% else %}
                    <p>No notes are available.</p>
                {% endif %}
                <form class="form-group" action="{% url 'notes_api:add_note' %}" method="post">
                    {% csrf_token %}
                    <label for="title">Title</label>
                    <input id="title" class="form-control" type="text" name="title">
                    <label for="body">Body</label>
                    <input id="body" class="form-control" type="text" name="body">
                    <br>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        {% else %}
            <form class="form-group" action="{% url 'login' %}">
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
            <form class="form-group" action="{% url 'signup' %}">
                <button type="submit" class="btn btn-primary">Sign Up</button>
            </form>

        {% endif %}
    </body>

</html>

social/templates/social/index.html
{% load static %}
<html>
    <header>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </header>
    <style>
        body {
            padding-top: 60px;
            padding-left: 60px;
            padding-right: 60px;
        }
    </style>
    <body>
        <h1>
            Social Page
        </h1>
        <p>
            Welcome, You are logged in as {{ user.username }}
        </p>
        {% if all_users %}
            <ul class="list-group">
                {% for cur_user in all_users %}
                    {% if cur_user.username != user.username %}
                        <li class="list-group-item">
                            <p style="display: inline-block; margin-right: 50px;">
                                {{ cur_user.username }}
                            </p>   
                            <form class="form-group" action="{% url 'social:home' %}"  style="display: inline-block;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-success">Follow</button>
                            </form>

                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        {% else %}
            <p>No users are available.</p>
        {% endif %}

            
        
    </body>

</html>